### PR TITLE
feat: checkbox input

### LINKED ISSUE #62: Update checkbox input to be viable
As a part of the [search v2](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/248) work, the designs call for two styles of checkbox.

- [x] Update checkbox input to properly handle change and input events.
- [x] Ensure checkbox input works as expected with form
- [x] Write tests to cover it
- [x] Update documentation
- [x] Raise PR against `beta`

### PR DESCRIPTION
**Pull request by joshuagraber**
Resolves #62 

## To test
1. Run `npm run dev`
3. Ensure that the test form works properly with the checkbox and it's styled appropriately

### CODE REVIEW

**Review by vikramrojo — COMMENTED** [review]
Took a look and have some feedback:
- I think the cursor should change to interactive click
- Possibly the click target should be larger

**Comment by joshuagraber** [comment]
> Possibly the click target should be larger

@vikramrojo Can you say more about this? The checkbox and its label are clickable. What part are you wanting to be larger?

**Comment by vikramrojo** [comment]
@joshuagraber maybe it was just the missing cursor, but I couldn't make out what the target area was. It looks good now.

**Review by vikramrojo — APPROVED** [review]
Design wise it looks good.

**Pull request merged**
