### PR TITLE
refactor: 2023 launch aesthetic tweaks

### LINKED ISSUE #36: 2023 launch visual refinements
- [x] quick search page
- [ ] results page
   - [ ] placeholder text cut off
   - [ ] cramped search results
   - [x] centered containers
   - [ ] label/value differentiation
- [ ] details page
- [x] left-aligned text
- [ ] mobile testing
   - [ ] quick search
   - [ ] results
   - [ ] details
- [x] switching between active nav items causes them to move around (switch to outline instead of border?)

### PR DESCRIPTION
**Pull request by josh-chamberlain**
fixes #36 

should be followed by https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/130

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
@joshuagraber this is about ready to be reviewed and applied to `data-sources-app` dev and `pdap.io` dev. Most (if not all)  remaining changes will be made to classes in `data-sources-app`.

**Comment by joshuagraber** [comment]
> this is about ready to be reviewed

Nice @josh-chamberlain! I also have some minor misc cleanup (docs, comments, etc.) I'd like to get in, are you good if I push those to this branch once you're ready?

**Comment by josh-chamberlain** [comment]
@joshuagraber sure thing! I will still rewrite the commits if you don't get to it but feel free to make any changes you'd like. it pairs with the `launch-refinements` branch of data-sources-app and `dev` branch of pdap.io

**Review by joshuagraber — DISMISSED** [review]

**Comment by joshuagraber** [comment]
Morning, @josh-chamberlain. I've added what I was hoping to here, re-wrote commit messages, and approved. Should be g2g. (FYI, I force-pushed after the rebasing to amend the commit messages, so probably need to force-pull or ort merge on your end, if you're pulling this to test locally.)

**Review by joshuagraber — APPROVED** [review]

**Comment by josh-chamberlain** [comment]
@joshuagraber nice, LGTM!

**Pull request merged**
